[package]
name = "client"
version = "0.1.0"
authors = ["Haskellknippe <kristian_hasselknippe@outlook.com>"]

[dependencies]
engine = { path = "../engine" }
gl = "*"
nalgebra-glm = "*"
alga = "*"
glutin = "*"
specs = "*"
specs-derive = "*"
