[package]
name = "shooter-client"
version = "0.1.0"
authors = ["Kristian Fjeld Hasselknippe <kristian_hasselknippe@outlook.com>"]

[dependencies]
gl = "0.6.0"
glfw = "0.14.0"
shooter_common = { path = "../shooter-common" }
nalgebra = "0.11"